---
- name: Install iptables
  yum:
    name: iptables-services
    state: present

- name: activate iptables service
  service:
    name: iptables
    state: started
    enabled: yes

- name: saving iptables config
  shell: service iptables save