---
- name: Enable firewalld
  sudo: yes
  service: enabled=true name=firewalld state=started
  tags: 
    - firewalld
    - service

- name: use 234 for firewalld module.
  sudo: yes
  firewalld: permanent={{ item.permanent }} port={{ item.port }}  state=enabled
  tags: 
    - firewalld
    - add_rule
  with_items: 
    - {port: 234/tcp, permanent: true}
    - {port: 234/tcp, permanent: false}


- name: setting and restart sshd.
  sudo: yes
  template: dest=/etc/ssh/sshd_config  src=sshd_config.j2
  notify: [restart sshd]
  tags: 
    - sshd
    - service