---
- name: getting source from repository
  git:
    dest: {{laravel_docroot}}{{item.name}}
    repo: git
    version: {{item.branch}}

- name: doing composer install
  command: composer install

- name: install artisan scheduler

- name: install artisan queue