---
- name: configure rpm to get php 5.6 (from webtatic)
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

- name: install php 5.6w and it's dependencies
  yum:
    name: "{{item}}"
    state: installed
  with_items: 
    - php56w
    - php56w-devel
    - php56w-xml
    - php56w-mbstring
    - php56w-mcrypt
    - php56w-pdo
    - php56w-pear
  register: phpinstall_result
  ignore_errors: True

- include: mongodb.yml
  tags: 
    - mongo

- include: imagick.yml
  tags:
    - imagick