---
- include: ../mongo_common/tasks/repo.yml

- name: Mongod template
  sudo: yes
  template: src=mongoc.config.j2 dest=/etc/mongod.conf

- include: ../mongo_common/tasks/install.yml

- name: mongoc init replset 
  sudo: yes
  template: src=replset_init.j2 dest=/opt/init_replset.js
  tags:
    -  mongoc
    -  template
    -  replset

- name: mongo replset initialize
  sudo: yes
  shell: mongo < init_replset.js chdir=/opt
  tags:
    - replset
    - mongoc
  when: groups['mongoc'][0] == ansible_eth0.ipv4.address